type InventoryImageKeyValuePair = {
  [key: string]: string;
};

export const InventoryItemImages: InventoryImageKeyValuePair = {
  "🐥": "🐥",
  avocado: "🥑",
  banana: "🍌",
  blueberry: "🫐",
  "chicken-egg": "🥚",
  "conch-shell": "🐚",
  "cool-feather": "🪶",
  "cool-shell": "🐚",
  "crab-claw": "🦀",
  croissant: "🥐",
  "crystal-ball": "🔮",
  cucumber: "🥒",
  diamond: "💎",
  daisy: "🌼",
  driftwood: "🪵",
  "irradiated-avocado": "🥑",
  "irradiated-croissant": "🥐",
  "irradiated-feather": "🪶",
  "irradiated-leaf": "🍂",
  "irradiated-pineapple": "🍍",
  "irradiated-stick-of-butter": "🧈",
  lemon: "🍋",
  "live-coral": "🪸",
  "lobster-claw": "🦞",
  "oyster-shell": "🦪",
  peach: "🍑",
  peanut: "🥜",
  pineapple: "🍍",
  "red-rose": "🌹",
  "stick-of-butter": "🧈",
  strawberry: "🍓",
  "three-leaf-clover": "☘️",
  tomato: "🍅",
  "toxic-waste": "☢️",
  watermelon: "🍉",
  "wooden-flute": "🪈",
  "whole-mango": "🥭",
};
